
#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {}

http {
    server {
        listen 80;
        server_name localhost;

        location = / {
            return 302 /home;
        }

        # FRONT NEXT
        location / {
            proxy_pass http://front-end:3000;

            proxy_http_version 1.1;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_set_header Host $host;
	    proxy_cache_bypass $http_upgrade;
        }

        # USER SERVICE
        location /api/users/ {
            proxy_pass http://user-service:3001/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

    }
}