
#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {}

http {
    server {
        listen 80;
        server_name localhost;

        location = / {
            return 302 /home;
        }

        # USER SERVICE
        location /api/users/ {
            proxy_pass https://user-service.railway.internal:3001;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # BOOK SERVICE
        location /api/books/{
            proxy_pass http://book-service.railway.internal:3002/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # TRANSACTION SERVICE
        location /api/transaction/{
            proxy_pass http://transaction-service.railway.internal:3003/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

    }
}