name: Frontend CI

on:
  push:
    paths:
      - 'front-end/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install
        working-directory: ./front-end/ownshelf-front

      - run: npm run build
        working-directory: ./front-end/ownshelf-front
