name: Transaction Service CI

on:
  push:
    paths:
      - 'back-end/transaction-service/**'

jobs:
  test:

    runs-on: ubuntu-latest

    env: 
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install
        working-directory: ./back-end/transaction-service

      - run: npm run build
        working-directory: ./back-end/transaction-service
